#!/usr/bin/env bash
# aroli-newtab-pywal.sh -- deriva o tema da new-tab a partir da paleta pywal.
#
# Custo em repouso: zero. Este script roda UMA vez por troca de wallpaper
# (chamado por set-wallpaper.sh) e escreve dois arquivos estáticos que a
# extensão lê sem polling, sem rede e sem timers:
#   ~/.config/aroli-newtab/theme-system.css   vars da página
#   ~/.config/aroli-newtab/theme-system.json  frame do Brave (chrome.theme)
# Sem paleta ainda, sai em silêncio mantendo a semente Aroli Dark.
J="$HOME/.cache/wal/colors.json"
OUT_DIR="$HOME/.config/aroli-newtab"
[ -f "$J" ] || exit 0
mkdir -p "$OUT_DIR" || exit 0

OUT=$(python3 - "$J" <<'PY'
import colorsys, json, math, sys

c = json.load(open(sys.argv[1]))
pal, sp = c["colors"], c["special"]
bg, fg = sp["background"], sp["foreground"]

def hls(h):
    h = h.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return colorsys.rgb_to_hls(r, g, b)

def hexof(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h % 1.0, min(max(l, 0), 1), min(max(s, 0), 1))
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))

def rgb(h):
    h = h.lstrip("#")
    return [int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)]

bh, bl, bs = hls(bg)
dark = bl < 0.5

cands = [hls(pal["color%d" % i]) for i in range(1, 7)]
ranked = sorted(cands, key=lambda t: t[2], reverse=True)
ah, al, a_s = ranked[0]
mean = math.atan2(sum(math.sin(t[0] * 2 * math.pi) for t in cands) / len(cands),
                  sum(math.cos(t[0] * 2 * math.pi) for t in cands) / len(cands)) / (2 * math.pi) % 1.0
def circ(a, b):
    d = abs(a - b) % 1.0
    return min(d, 1.0 - d)
if len(ranked) > 1 and circ(ah, mean) > 0.25 and circ(ranked[1][0], mean) <= 0.25:
    ah, al, a_s = ranked[1]
if a_s < 0.08:
    ah, al, a_s = hls(fg)
s_acc = min(max(a_s, 0.15) + 0.10, 0.50)

step = 0.035 if dark else -0.035
surface = hexof(bh, bl + step, bs)
raised = hexof(bh, bl + step * 1.6, bs)
hover = hexof(bh, bl + step * 2.2, bs)
border = hexof(bh, bl + step * 2.2, min(bs, 0.18))
border_hi = hexof(bh, bl + step * 3.4, min(bs + 0.05, 0.25))
deep = hexof(bh, max(bl - step, 0), bs)
inactive = hexof(bh, max(bl - step * 2, 0), bs)

def _lin(x):
    return x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4

def lum(h):
    h = h.lstrip("#")
    r, g, b = (_lin(int(h[i:i + 2], 16) / 255) for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b

def ratio(a, b):
    la, lb = sorted((lum(a), lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)

def readable(col, target):
    h, l, s = hls(col)
    for _ in range(60):
        if ratio(hexof(h, l, s), bg) >= target:
            break
        l = min(l + 0.02, 1.0) if dark else max(l - 0.02, 0.0)
    return hexof(h, l, s)

accent = readable(hexof(ah, 0.55 if dark else 0.45, s_acc), 3.0)
link = readable(hexof(ah, 0.65 if dark else 0.38, s_acc), 4.5)
muted = readable(hexof(bh, bl + (0.35 if dark else -0.35), bs * 0.6), 4.0)
faint = readable(hexof(bh, bl + (0.22 if dark else -0.22), bs * 0.5), 3.0)
accent_ink = bg if ratio(bg, accent) >= ratio(fg, accent) else fg

print("/* generated by aroli-newtab-pywal.sh (automatic; do not edit) */")
print('html[data-theme="system"] {')
print("  --nt-bg: %s;" % bg)
print("  --nt-deep: %s;" % deep)
print("  --nt-surface: %s;" % surface)
print("  --nt-raised: %s;" % raised)
print("  --nt-hover: %s;" % hover)
print("  --nt-border: %s;" % border)
print("  --nt-border-hi: %s;" % border_hi)
print("  --nt-fg: %s;" % fg)
print("  --nt-muted: %s;" % muted)
print("  --nt-faint: %s;" % faint)
print("  --nt-accent: %s;" % accent)
print("  --nt-accent-ink: %s;" % accent_ink)
print("  --nt-link: %s;" % link)
print("}")
print("/*__AROLI_JSON__*/")
print(json.dumps({
    "_note": "generated by aroli-newtab-pywal.sh (automatic; do not edit)",
    "colors": {
        "frame": rgb(bg),
        "frame_inactive": rgb(inactive),
        "frame_incognito": rgb(deep),
        "frame_incognito_inactive": rgb(deep),
        "toolbar": rgb(surface),
        "tab_text": rgb(fg),
        "tab_background_text": rgb(faint),
        "toolbar_text": rgb(fg),
        "toolbar_button_icon": rgb(muted),
        "omnibox_text": rgb(fg),
        "omnibox_background": rgb(surface),
        "bookmark_text": rgb(fg),
        "ntp_background": rgb(bg),
        "ntp_text": rgb(fg),
        "ntp_link": rgb(link),
        "button_background": rgb(accent),
    },
}, indent=2))
PY
) || exit 0

CSS=$(printf '%s\n' "$OUT" | sed '/^\/\*__AROLI_JSON__\*\/$/q' | sed '$d')
JSON=$(printf '%s\n' "$OUT" | sed -n '/^\/\*__AROLI_JSON__\*\/$/,$p' | tail -n +2)

# Não publica sem as chaves: o tema anterior é melhor que um quebrado.
case "$CSS" in
  *'--nt-bg:'*'--nt-accent:'*) : ;;
  *) exit 0 ;;
esac
case "$JSON" in
  *'"frame"'*'"ntp_background"'*) : ;;
  *) exit 0 ;;
esac

TMP=$(mktemp "$OUT_DIR/theme-system.css.tmp.XXXXXX") || exit 0
printf '%s\n' "$CSS" > "$TMP" && mv "$TMP" "$OUT_DIR/theme-system.css" || rm -f "$TMP"
TMP=$(mktemp "$OUT_DIR/theme-system.json.tmp.XXXXXX") || exit 0
printf '%s\n' "$JSON" > "$TMP" && mv "$TMP" "$OUT_DIR/theme-system.json" || rm -f "$TMP"

# Frame pelo canal oficial: BrowserThemeColor é policy gerenciada e vence
# chrome.theme no frame; brigar com o arquivo é inútil (o Omarchy o
# reinstala). O escritor tem sudo sem senha e o refresh reaplica sem
# reiniciar o navegador. Nunca falha o pipeline.
if command -v omarchy-theme-set-browser-policy >/dev/null 2>&1; then
  BGHEX=$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['special']['background'])" "$J" 2>/dev/null)
  case "$BGHEX" in
    '#'??????)
      sudo -n omarchy-theme-set-browser-policy "${BGHEX#'#'}" >/dev/null 2>&1 || true
      if pgrep -f /opt/brave-origin-bin/brave-origin >/dev/null 2>&1; then
        (brave-origin --refresh-platform-policy --no-startup-window >/dev/null 2>&1 &) || true
      fi
      ;;
  esac
fi
exit 0
